# Site settings
title: Basic static site for Media,Tech, and Gender presentation.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a site built while preparing a presentation focus on Media, Technology and Gender.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mediatechgender.com" # the base hostname & protocol for your site
twitter_username: n/a
github_username:  mediatechgender

# Build settings
markdown: kramdown
